In [38]:
# add folders to Python's search space
import os, sys
from pathlib import Path
script_dir = Path(os.path.dirname(os.path.abspath('')))
module_dir = str(script_dir)
sys.path.insert(0, module_dir + '/modules')
print(module_dir)

# import the rest of the modules
%matplotlib nbagg
%matplotlib inline
import numpy as np
import tensorflow as tf 
import matplotlib.pyplot as plt
import arch
import pandas as pd
import tensorflow_probability as tfp
import time  
import sim
from mpl_toolkits.axes_grid1 import make_axes_locatable
import warnings
DTYPE = 'float32'
warnings.filterwarnings('ignore')

C:\Users\pinak\Documents\GitHub\fp-solvers


In [3]:
dim = 3
net = arch.LSTMForgetNet(50, 3, tf.float32, name="L63")
net.load_weights('../non-grad3D/data/L63/1M/{}'.format(net.name)).expect_partial()
X = tf.random.uniform(shape=(10, dim))
net(*tf.split(X, dim, axis=-1))

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[2.7304213],
       [2.4110296],
       [2.47568  ],
       [2.68868  ],
       [2.5848808],
       [2.4806106],
       [2.6551466],
       [2.6394653],
       [2.644019 ],
       [2.354955 ]], dtype=float32)>

In [32]:
X = np.random.normal(size=(10, 100, 3))
l = np.array([-1, -1, -1])
h = -l
a = np.zeros((10, 100))

In [33]:
for i in range(10):
    a[i, :] = (np.sum(np.sign((X[2]-l)*(h-X[2])), axis=-1)==3).astype(float)

In [34]:
mask = a.T == 0.
f = np.where(mask.any(1), mask.argmax(1), -1)

In [35]:
f

array([-1, -1,  0,  0,  0,  0, -1, -1,  0,  0, -1, -1,  0,  0,  0,  0,  0,
       -1, -1, -1, -1,  0,  0, -1,  0, -1,  0,  0, -1, -1,  0,  0,  0, -1,
        0, -1,  0, -1,  0, -1,  0,  0,  0,  0,  0, -1, -1,  0, -1, -1,  0,
        0,  0, -1,  0,  0, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0,  0, -1,  0,  0, -1,  0,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
      dtype=int64)

In [36]:
for i in f:
    if i > -1:
        a[i:, :] *= 0

In [37]:
a.T

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [41]:
X[2] #- np.array([1., 0., -1.])

array([[ 0.21888328, -0.79959945,  0.45243116],
       [ 0.33753238, -0.6876177 ,  0.40004945],
       [-0.59006366,  0.01036338, -1.79467406],
       [-1.11984264, -1.16805986, -1.65210174],
       [ 0.52081548, -1.34807882,  0.96564628],
       [ 0.75554165, -1.38358952, -0.29141686],
       [ 0.41194542, -0.65991394, -0.38684967],
       [-0.17684613, -0.79934331,  0.44123924],
       [-0.76858581,  1.31847845,  0.54742027],
       [ 0.05451919, -1.09133811,  0.46696653],
       [ 0.16725778,  0.14224427,  0.15357697],
       [-0.96184902, -0.18276137, -0.23786165],
       [ 1.05374264, -0.49452156, -0.75370374],
       [ 1.73708411,  0.42362278,  0.5380689 ],
       [ 1.30583483, -1.46687798, -0.41369825],
       [ 0.31005753,  0.75061936,  1.04527303],
       [ 0.60679332,  1.4066773 , -0.55564767],
       [-0.39788645,  0.1022575 ,  0.52358413],
       [ 0.5819236 , -0.60729329,  0.40517254],
       [ 0.57119065, -0.70487468,  0.54956702],
       [-0.11451006,  0.3656932 ,  0.728