In [1]:
import numpy as np 

a, b, n = 1., 2., 10
u = np.linspace(a, b, num=n)
nu = np.random.uniform(low=a, high=b, size=n)

In [2]:
u

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [3]:
nu

array([1.46717624, 1.51107223, 1.55497279, 1.70084361, 1.01327453,
       1.20709298, 1.2420358 , 1.68525695, 1.88873102, 1.39830483])

In [4]:
h = (b-a)/(n-1)

In [5]:
p, w  = np.polynomial.legendre.leggauss(7)

In [6]:
h

0.1111111111111111

In [7]:
((nu - u[0])/h).astype(int)

array([4, 4, 4, 6, 0, 1, 2, 6, 7, 3])

In [8]:
x = np.random.uniform(size=(5, 3))

In [9]:
np.transpose(x, (1, 2, 0))

ValueError: axes don't match array

In [ ]:
x

In [ ]:
x[:, [1,2,0]]

In [ ]:
a = np.ones(3)

In [ ]:
(x - a).astype(int)

In [ ]:
p = np.random.randint(5, size=[5, 3])

In [ ]:
p

In [ ]:
p[np.where((p[:, 0]==0)*(p[:, 1]==0))][:,-1]

In [ ]:
np.unique(p[:, [0, 1]], axis=0)

In [ ]:
p

In [ ]:
p[1] = [3, 2, 1]

In [ ]:
p

In [ ]:
np.unique(p[:, [0,1]], return_counts=False, axis=0)

In [ ]:
a

In [ ]:
b

In [ ]:
a[0]=-1

In [ ]:
b

In [20]:
list({0, 1, 2} -{0, 2})[0]

1

In [16]:
np.arange(1., 2.+0.1, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])